core/urls.py
from django.urls import path, include
from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='homeview'),
    path('courses/', CourseView.as_view(), name='CourseView'),
    path('', include('products.urls'), name='CourseDetailsView'),
    path('', include('accounts.urls'), name='ProfileView'),
    path('login/', login123, name='LoginView'),
    path('register/', register_page, name='RegisterView'),
    path('cart', CartView.as_view(), name='CartView'),
    path('about/', AboutView.as_view(), name='AboutView'),
    path('contact/', ContactView.as_view(), name='ContactView'),
    path('blog/', BlogView.as_view(), name='BlogView'),
    path('blog-details/', BlogDetailsView.as_view(), name='BlogDetailsView'),
    path('events/', EventView.as_view(), name='EventView'),
    path('event-details/', EventDetailsView.as_view(), name='EventDetailsView'),
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    
    
]

about/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from accounts.models import CustomerUser

# Create your models here.

class Category(models.Model):
    title = models.CharField(default="", max_length=255)
    slug = models.CharField(default="", max_length=100)
    description = models.TextField(default="")
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class News(models.Model):
    title = models.CharField(default="", max_length=255)
    slug = models.CharField(default="", max_length=100)
    image_course = models.ImageField(default=None, upload_to='static/media/blog')
    content = models.TextField(default="")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.title


class Comment(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    comment = models.TextField(default = "")
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.comment

contact/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models
from accounts.models import CustomerUser

# Create your models here.

class CategoryEvent(models.Model):
    title = models.CharField(default="", max_length=255)
    slug = models.CharField(default="", max_length=100)
    description = models.TextField(default="")
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Events(models.Model):
    title = models.CharField(default="", max_length=255)
    slug = models.CharField(default="", max_length=100)
    image_course = models.ImageField(default=None, upload_to='static/media/event')
    content = models.TextField(default="")
    category = models.ForeignKey(CategoryEvent, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.title


class CommentEvent(models.Model):
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    comment = models.TextField(default = "")
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.comment

footer/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

footer/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<!-- META ============================================= -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	
	<!-- DESCRIPTION -->
	<meta name="description" content="{{ title }}" />
	
	<!-- OG -->
	<meta property="og:title" content="{{ title }}" />
	<meta property="og:description" content="{{ title }}" />
	<meta property="og:image" content="" />
	<meta name="format-detection" content="telephone=no">
	
	<!-- FAVICONS ICON ============================================= -->
	<link rel="icon" href="{% static 'homepage/images/favicon.ico' %}" type="image/x-icon" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'homepage/images/favicon.png' %}" />
	
	<!-- PAGE TITLE HERE ============================================= -->
	<title>{{ title }}</title>
	
	<!-- MOBILE SPECIFIC ============================================= -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!--[if lt IE 9]>
	<script src="{% static 'homepage/js/html5shiv.min.js"></script>
	<script src="{% static 'homepage/js/respond.min.js"></script>
	<![endif]-->
	
	<!-- All PLUGINS CSS ============================================= -->
	
<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/assets.css' %}">
	
	<!-- TYPOGRAPHY ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/typography.css' %}">
	
	<!-- SHORTCODES ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/shortcodes/shortcodes.css' %}">
	
	<!-- STYLESHEETS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/style.css' %}">
	<link class="skin" rel="stylesheet" type="text/css" href="{% static 'homepage/css/color/color-1.css' %}">
	
	<!-- REVOLUTION SLIDER CSS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendors/revolution/css/layers.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendors/revolution/css/settings.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendors/revolution/css/navigation.css' %}">
	<!-- REVOLUTION SLIDER END -->

</head>
<body id="bg">

{% include 'header.html' %}

{% block content %}
{% endblock %}

{% include 'footer.html' %}

<!-- External JavaScripts -->
<script src="{% static 'homepage/js/jquery.min.js' %}"></script>
<script src="{% static 'homepage/vendors/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'homepage/vendors/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'homepage/vendors/bootstrap-select/bootstrap-select.min.js' %}"></script>
<script src="{% static 'homepage/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js' %}"></script>
<script src="{% static 'homepage/vendors/magnific-popup/magnific-popup.js' %}"></script>
<script src="{% static 'homepage/vendors/counter/waypoints-min.js' %}"></script>
<script src="{% static 'homepage/vendors/counter/counterup.min.js' %}"></script>
<script src="{% static 'homepage/vendors/imagesloaded/imagesloaded.js' %}"></script>
<script src="{% static 'homepage/vendors/masonry/masonry.js' %}"></script>
<script src="{% static 'homepage/vendors/masonry/filter.js' %}"></script>
<script src="{% static 'homepage/vendors/owl-carousel/owl.carousel.js' %}"></script>
<script src="{% static 'homepage/js/functions.js' %}"></script>
<script src="{% static 'homepage/js/contact.js' %}"></script>
<script src="{% static 'homepage/vendors/switcher/switcher.js' %}"></script>
<!-- Revolution JavaScripts Files -->
<script src="{% static 'homepage/vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
<!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'homepage/vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
<script>
jQuery(document).ready(function() {
	var ttrevapi;
	var tpj =jQuery;
	if(tpj("#rev_slider_486_1").revolution == undefined){
		revslider_showDoubleJqueryError("#rev_slider_486_1");
	}else{
		ttrevapi = tpj("#rev_slider_486_1").show().revolution({
			sliderType:"standard",
			jsFileLocation:"{% static 'homepage/vendors/revolution/js/' %}",
			sliderLayout:"fullwidth",
			dottedOverlay:"none",
			delay:9000,
			navigation: {
				keyboardNavigation:"on",
				keyboard_direction: "horizontal",
				mouseScrollNavigation:"off",
				mouseScrollReverse:"default",
				onHoverStop:"on",
				touch:{
					touchenabled:"on",
					swipe_threshold: 75,
					swipe_min_touches: 1,
					swipe_direction: "horizontal",
					drag_block_vertical: false
				}
				,
				arrows: {
					style: "uranus",
					enable: true,
					hide_onmobile: false,
					hide_onleave: false,
					tmp: '',
					left: {
						h_align: "left",
						v_align: "center",
						h_offset: 10,
						v_offset: 0
					},
					right: {
						h_align: "right",
						v_align: "center",
						h_offset: 10,
						v_offset: 0
					}
				},
				
			},
			viewPort: {
				enable:true,
				outof:"pause",
				visible_area:"80%",
				presize:false
			},
			responsiveLevels:[1240,1024,778,480],
			visibilityLevels:[1240,1024,778,480],
			gridwidth:[1240,1024,778,480],
			gridheight:[768,600,600,600],
			lazyType:"none",
			parallax: {
				type:"scroll",
				origo:"enterpoint",
				speed:400,
				levels:[5,10,15,20,25,30,35,40,45,50,46,47,48,49,50,55],
				type:"scroll",
			},
			shadow:0,
			spinner:"off",
			stopLoop:"off",
			stopAfterLoops:-1,
			stopAtSlide:-1,
			shuffle:"off",
			autoHeight:"off",
			hideThumbsOnMobile:"off",
			hideSliderAtLimit:0,
			hideCaptionAtLimit:0,
			hideAllCaptionAtLilmit:0,
			debugMode:false,
			fallbacks: {
				simplifyAll:"off",
				nextSlideOnWindowFocus:"off",
				disableFocusListener:false,
			}
		});
	}
});	
</script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        <div class="page-banner ovbl-dark" style="background-image:url(assets/images/banner/banner3.jpg);">
            <div class="container">
                <div class="page-banner-entry">
                    <h1 class="text-white">Contact Us 1</h1>
				 </div>
            </div>
        </div>
		<!-- Breadcrumb row -->
		<div class="breadcrumb-row">
			<div class="container">
				<ul class="list-inline">
					<li><a href="#">Home</a></li>
					<li>Contact Us 1</li>
				</ul>
			</div>
		</div>
		<!-- Breadcrumb row END -->
	
        <!-- inner page banner -->
        <div class="page-banner contact-page section-sp2">
            <div class="container">
                <div class="row">
					<div class="col-lg-5 col-md-5 m-b30">
						<div class="bg-primary text-white contact-info-bx">
							<h2 class="m-b10 title-head">Contact <span>Information</span></h2>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
							<div class="widget widget_getintuch">	
								<ul>
									<li><i class="ti-location-pin"></i>75k Newcastle St. Ponte Vedra Beach, FL 309382 New York</li>
									<li><i class="ti-mobile"></i>0800-123456 (24/7 Support Line)</li>
									<li><i class="ti-email"></i>info@example.com</li>
								</ul>
							</div>
							<h5 class="m-t0 m-b20">Follow Us</h5>
							<ul class="list-inline contact-social-bx">
								<li><a href="#" class="btn outline radius-xl"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#" class="btn outline radius-xl"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#" class="btn outline radius-xl"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#" class="btn outline radius-xl"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
					
					<div class="col-lg-7 col-md-7">
						{{ form }}{% csrf_token %}
						<div class="col-lg-12">
							<button name="submit" type="submit" value="Submit" class="btn button-md"> Send Message</button>
						</div>
						<form class="contact-bx ajax-form" action="http://educhamp.themetrades.com/demo/assets/script/contact.php">
						<div class="ajax-message"></div>
							<div class="heading-bx left">
								<h2 class="title-head">Get In <span>Touch</span></h2>
								<p>It is a long established fact that a reader will be distracted by the readable content of a page</p>
							</div>
							<div class="row placeani">
								<div class="col-lg-6">
									<div class="form-group">
										<div class="input-group">
											<label>Your Name</label>
											<input name="name" type="text" required class="form-control valid-character">
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<div class="input-group"> 
											<label>Your Email Address</label>
											<input name="email" type="email" class="form-control" required >
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<div class="input-group">
											<label>Your Phone</label>
											<input name="phone" type="text"  required class="form-control int-value">
										</div>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<div class="input-group">
											<label>Subject</label>
											<input name="subject" type="text" required class="form-control">
										</div>
									</div>
								</div>
								<div class="col-lg-12">
									<div class="form-group">
										<div class="input-group">
											<label>Type Message</label>
											<textarea name="message" rows="4" class="form-control" required ></textarea>
										</div>
									</div>
								</div>
								<div class="col-lg-12">
									<div class="form-group">
										<div class="input-group">
											<div class="g-recaptcha" data-sitekey="6Lf2gYwUAAAAAJLxwnZTvpJqbYFWqVyzE-8BWhVe" data-callback="verifyRecaptchaCallback" data-expired-callback="expiredRecaptchaCallback"></div>
											<input class="form-control d-none" style="display:none;" data-recaptcha="true" required data-error="Please complete the Captcha">
										</div>
									</div>
								</div>
								<div class="col-lg-12">
									<button name="submit" type="submit" value="Submit" class="btn button-md"> Send Message</button>
								</div>
							</div>
						</form>
					</div>
				</div>
            </div>
		</div>
        <!-- inner page banner END -->
    </div>
    <!-- Content END-->

  
{% endblock content %}

templates/css.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/assets.css' %}">
	
	<!-- TYPOGRAPHY ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/typography.css' %}">
	
	<!-- SHORTCODES ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/shortcodes/shortcodes.css' %}">
	
	<!-- STYLESHEETS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/style.css' %}">
	<link class="skin" rel="stylesheet" type="text/css" href="{% static 'homepage/css/color/color-1.css' %}">
	
	<!-- REVOLUTION SLIDER CSS ============================================= -->
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendors/revolution/css/layers.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendors/revolution/css/settings.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendors/revolution/css/navigation.css' %}">
	<!-- REVOLUTION SLIDER END -->	

templates/error-404.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="page-wraper">
	<div id="loading-icon-bx"></div>
	<div class="account-form">
		<div class="account-head" style="background-image:url(assets/images/background/bg2.jpg);">
			<a href="index.html"><img src="assets/images/logo-white-2.png" alt=""></a>
		</div>
		<div class="account-form-inner">
			<div class="account-container">
				<div class="error-page">
					<h3>Ooopps :(</h3>
					<h2 class="error-title">404</h2>
					<h5>The Page you were looking for, couldn't be found.</h5>
					<p>The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</p>
					<div class="">
						<a href="index.html" class="btn m-r5">Preview</a>
						<a href="index.html" class="btn outline black">Back To Home</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

templates/header.html
{% load static %}
<header class="header rs-nav">
		<div class="top-bar">
			<div class="container">
				<div class="row d-flex justify-content-between">
					<div class="topbar-left">
						<ul>
							<li><a href="faq-1.html"><i class="fa fa-question-circle"></i>Ask a Question</a></li>
							<li><a href="javascript:;"><i class="fa fa-envelope-o"></i>Support@website.com</a></li>
						</ul>
					</div>
					<div class="topbar-right">
						<ul>
							<li>
								<select class="header-lang-bx">
									<option data-icon="flag flag-uk">English UK</option>
									<option data-icon="flag flag-us">English US</option>
								</select>
							</li>
							<li><a href="{% url 'core:LoginView' %}">Login</a></li>
							<li><a href="{% url 'core:RegisterView' %}">Register</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="sticky-header navbar-expand-lg">
            <div class="menu-bar clearfix">
                <div class="container clearfix">
					<!-- Header Logo ==== -->
					<div class="menu-logo">
						<a href="{% url 'core:homeview' %}"><img src="{% static 'homepage/images/logo.png' %}" alt=""></a>
					</div>
					<!-- Mobile Nav Button ==== -->
                    <button class="navbar-toggler collapsed menuicon justify-content-end" type="button" data-toggle="collapse" data-target="#menuDropdown" aria-controls="menuDropdown" aria-expanded="false" aria-label="Toggle navigation">
						<span></span>
						<span></span>
						<span></span>
					</button>
					<!-- Author Nav ==== -->
                    <div class="secondary-menu">
                        <div class="secondary-inner">
                            <ul>
								<li><a href="javascript:;" class="btn-link"><i class="fa fa-facebook"></i></a></li>
								<li><a href="javascript:;" class="btn-link"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="javascript:;" class="btn-link"><i class="fa fa-linkedin"></i></a></li>
								<!-- Search Button ==== -->
								<li class="search-btn"><button id="quik-search-btn" type="button" class="btn-link"><i class="fa fa-search"></i></button></li>
							</ul>
						</div>
                    </div>
					<!-- Search Box ==== -->
                    <div class="nav-search-bar">
                        <form action="#">
                            <input name="search" value="" type="text" class="form-control" placeholder="Type to search">
                            <span><i class="ti-search"></i></span>
                        </form>
						<span id="search-remove"><i class="ti-close"></i></span>
                    </div>
					<!-- Navigation Menu ==== -->
                    <div class="menu-links navbar-collapse collapse justify-content-start" id="menuDropdown">
						<div class="menu-logo">
							<a href="{% url 'core:homeview' %}"><img src="{% static 'homepage/images/logo.png' %}" alt=""></a>
						</div>
                        <ul class="nav navbar-nav">	
							<li class="nav-item active"><a class="nav-link" href="{% url 'core:homeview' %}">Home </a></li>
							<li class="nav-item "><a class="nav-link" href="{% url 'core:AboutView' %}">About </a></li>
							<li class="nav-item "><a class="nav-link" href="{% url 'core:CourseView' %}">Course </a>
								
							</li>
							<li class="nav-item "><a class="nav-link" href="{% url 'core:EventView' %}">Event </a>

							</li>
							<li class="nav-item "><a class="nav-link" href="{% url 'core:BlogView' %}">Blog </a>

							</li>
							<li class="nav-item "><a class="nav-link" href="{% url 'core:ContactView' %}">Contact </a></li>
							

							<!-- <li class="active"><a href="{% url 'core:homeview' %}">Home <i ></i></a></li>
							<li><a href="javascript:;">Pages <i class="fa fa-chevron-down"></i></a>
								<ul class="sub-menu">
									<li><a href="javascript:;">About<i class="fa fa-angle-right"></i></a>
										<ul class="sub-menu">
											<li><a href="about-1.html">About 1</a></li>
											<li><a href="about-2.html">About 2</a></li>
										</ul>
									</li>
									<li><a href="javascript:;">Event<i class="fa fa-angle-right"></i></a>
										<ul class="sub-menu">
											<li><a href="event.html">Event</a></li>
											<li><a href="events-details.html">Events Details</a></li>
										</ul>
									</li>
									<li><a href="javascript:;">FAQ's<i class="fa fa-angle-right"></i></a>
										<ul class="sub-menu">
											<li><a href="faq-1.html">FAQ's 1</a></li>
											<li><a href="faq-2.html">FAQ's 2</a></li>
										</ul>
									</li>
									<li><a href="javascript:;">Contact Us<i class="fa fa-angle-right"></i></a>
										<ul class="sub-menu">
											<li><a href="contact-1.html">Contact Us 1</a></li>
											<li><a href="contact-2.html">Contact Us 2</a></li>
										</ul>
									</li>
									<li><a href="portfolio.html">Portfolio</a></li>
									<li><a href="profile.html">Profile</a></li>
									<li><a href="membership.html">Membership</a></li>
									<li><a href="error-404.html">404 Page</a></li>
								</ul>
							</li>
							<li class="add-mega-menu"><a href="javascript:;">Our Courses <i class="fa fa-chevron-down"></i></a>
								<ul class="sub-menu add-menu">
									<li class="add-menu-left">
										<h5 class="menu-adv-title">Our Courses</h5>
										<ul>
											<li><a href="courses.html">Courses </a></li>
											<li><a href="courses-details.html">Courses Details</a></li>
											<li><a href="profile.html">Instructor Profile</a></li>
											<li><a href="event.html">Upcoming Event</a></li>
											<li><a href="membership.html">Membership</a></li>
										</ul>
									</li>
									<li class="add-menu-right">
										<img src="{% static 'homepage/images/adv/adv.jpg' %}" alt=""/>
									</li>
								</ul>
							</li>
							<li><a href="javascript:;">Blog <i class="fa fa-chevron-down"></i></a>
								<ul class="sub-menu">
									<li><a href="blog-classic-grid.html">Blog Classic</a></li>
									<li><a href="blog-classic-sidebar.html">Blog Classic Sidebar</a></li>
									<li><a href="blog-list-sidebar.html">Blog List Sidebar</a></li>
									<li><a href="blog-standard-sidebar.html">Blog Standard Sidebar</a></li>
									<li><a href="blog-details.html">Blog Details</a></li>
								</ul>
							</li>
							<li class="nav-dashboard"><a href="javascript:;">Dashboard <i class="fa fa-chevron-down"></i></a>
								<ul class="sub-menu">
									<li><a href="admin/index.html">Dashboard</a></li>
									<li><a href="admin/add-listing.html">Add Listing</a></li>
									<li><a href="admin/bookmark.html">Bookmark</a></li>
									<li><a href="admin/courses.html">Courses</a></li>
									<li><a href="admin/review.html">Review</a></li>
									<li><a href="admin/teacher-profile.html">Teacher Profile</a></li>
									<li><a href="admin/user-profile.html">User Profile</a></li>
									<li><a href="javascript:;">Calendar<i class="fa fa-angle-right"></i></a>
										<ul class="sub-menu">
											<li><a href="admin/basic-calendar.html">Basic Calendar</a></li>
											<li><a href="admin/list-view-calendar.html">List View Calendar</a></li>
										</ul>
									</li>
									<li><a href="javascript:;">Mailbox<i class="fa fa-angle-right"></i></a>
										<ul class="sub-menu">
											<li><a href="admin/mailbox.html">Mailbox</a></li>
											<li><a href="admin/mailbox-compose.html">Compose</a></li>
											<li><a href="admin/mailbox-read.html">Mail Read</a></li>
										</ul>
									</li>
								</ul>
							</li> -->
						</ul>
						<div class="nav-social-link">
							<a href="javascript:;"><i class="fa fa-facebook"></i></a>
							<a href="javascript:;"><i class="fa fa-google-plus"></i></a>
							<a href="javascript:;"><i class="fa fa-linkedin"></i></a>
						</div>
                    </div>
					<!-- Navigation Menu END ==== -->
                </div>
            </div>
        </div>
 </header>